MONGODB_HOST: mongodb-{{ env }}.daws90s.space
REDIS_HOST: redis-{{ env }}.daws90s.space
MYSQL_HOST: mysql-{{ env }}.daws90s.space 
RABBITMQ_HOST: rabbitmq-{{ env }}.daws90s.space 
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.daws90s.space
USER_HOST: user.backend-alb-{{ env }}.daws90s.space
CART_HOST: cart.backend-alb-{{ env }}.daws90s.space
SHIPPING_HOST: shipping.backend-alb-{{ env }}.daws90s.space
PAYMENT_HOST: payment.backend-alb-{{ env }}.daws90s.space